# TP 1 : Préparation des données

Le but de ce TP est d'extraire d'un fichier csv des matrices de données exploitables sur `NumPy`. Pour ce faire, il est utile d'utiliser la librairie `Pandas` qui permet la manipulation des données au format tabulaire.

In [3]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import string

Mounted at /content/drive

Il vous faudra manipuler des données textuelles avec Pandas (**[documentation](https://pandas.pydata.org/docs/user_guide/text.html)**).

## Exercice 1

Vous venez de recevoir l'extraction de la base de données sous le nom `clothes_data_1.csv`. Avant toute analyse, vous devez charger les données et garantir que chaque ligne correspond à un objet unique.

1. Chargez le fichier `clothes_data_1.csv` dans un DataFrame nommé `df`.

In [4]:
## Écrivez votre code ici.

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/clothes_data_1.csv")

2. Affichez les 5 premières lignes pour visualiser la structure.

In [5]:
## Écrivez votre code ici.
df.iloc[0:5]

          id      prix                                              image
0  BER-XNBX3   45.02 €  0 0 0 0 0 0 0 0 0 15 204 160 162 162 156 159 1...
1   AM-SZRNE   43.59 €  0 0 0 0 0 0 0 0 0 0 149 99 50 14 8 42 89 145 0...
2   AM-K7U1L  113.32 €  0 0 0 0 0 0 0 0 0 154 164 141 140 129 87 123 1...
3   AM-GVPN3  119.73 €  0 0 0 0 0 0 0 0 0 78 152 109 0 0 0 0 106 133 6...
4   AM-5XTIT   146.2 €  0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 7 1 ...

3. Affichez les dimensions du jeu de données (nombre de lignes et colonnes) avant nettoyage.

In [6]:
## Écrivez votre code ici.
df.shape

(3150, 3)

4. Identifiez et supprimez les doublons basés sur l'identifiant (`id`).

In [7]:
## Écrivez votre code ici.
df=df.drop_duplicates(subset=["id"])

5. Affichez les nouvelles dimensions pour confirmer le nettoyage.

In [8]:
## Écrivez votre code ici.
df.shape

(3000, 3)

## Exercice 2

Nous souhaitons connaître le prix moyen sur ce jeu de données. Pour ce faire, on utilise généralement la méthode `mean` des DataFrames de Pandas.

In [9]:
print(df['prix'].mean())

TypeError: Could not convert string '45.02 €43.59 €113.32 €119.73 €146.2 €74.43 €63.67 €124.16 €65.98 €142.93 €104.35 €78.21 €48.8 €60.57 €129.35 €44.03 €82.81 €46.05 €174.77 €53.13 €50.29 €73.17 €100.07 €120.35 €95.13 €110.96 €60.88 €42.54 €67.65 €157.42 €55.01 €115.08 €61.0 €83.41 €56.51 €59.2 €96.98 €39.78 €68.11 €150.62 €111.06 €62.37 €95.65 €105.78 €76.35 €49.84 €108.53 €71.74 €51.48 €94.82 €97.78 €70.82 €42.95 €96.93 €73.89 €93.14 €57.0 €67.77 €46.78 €114.8 €38.37 €35.87 €120.56 €134.58 €138.12 €51.04 €107.24 €63.44 €41.29 €136.95 €50.59 €95.59 €146.75 €63.03 €53.13 €86.25 €86.99 €133.6 €53.08 €141.11 €65.94 €44.92 €177.46 €133.63 €71.79 €129.87 €50.96 €116.17 €88.2 €60.88 €79.22 €81.56 €66.74 €76.67 €156.07 €70.44 €63.23 €90.34 €139.0 €67.15 €64.16 €120.0 €79.18 €55.32 €81.0 €74.54 €105.72 €98.48 €45.2 €55.41 €75.31 €64.16 €41.01 €96.95 €131.79 €61.74 €66.26 €160.33 €65.33 €129.13 €133.22 €66.03 €51.13 €112.98 €64.43 €155.09 €46.97 €92.1 €73.09 €51.66 €81.79 €99.5 €89.55 €40.03 €32.1 €55.71 €106.84 €95.74 €61.32 €120.42 €54.17 €76.45 €115.17 €40.25 €70.25 €45.73 €131.87 €90.67 €69.71 €55.75 €79.58 €48.26 €54.14 €83.69 €75.92 €83.5 €150.15 €47.6 €45.18 €53.82 €148.41 €49.37 €145.45 €76.88 €46.45 €39.75 €147.34 €44.25 €126.22 €102.84 €70.42 €132.85 €46.23 €76.19 €82.53 €114.44 €42.8 €67.53 €85.47 €125.23 €108.6 €145.32 €111.74 €56.28 €85.54 €125.17 €140.87 €66.26 €48.84 €147.39 €151.24 €70.64 €126.26 €68.97 €122.84 €99.48 €58.81 €72.54 €125.68 €71.07 €138.51 €73.65 €85.79 €38.89 €140.06 €100.71 €51.63 €78.88 €73.54 €38.08 €86.77 €118.84 €121.55 €87.66 €95.17 €60.76 €72.96 €136.0 €47.18 €78.73 €43.9 €50.18 €165.97 €64.7 €52.58 €84.83 €100.14 €100.18 €124.63 €100.53 €83.23 €88.5 €124.76 €163.88 €56.38 €129.17 €138.87 €81.76 €64.06 €60.77 €155.02 €98.26 €143.17 €91.09 €62.9 €46.39 €83.52 €61.68 €108.47 €84.04 €89.92 €98.84 €91.68 €71.17 €84.36 €141.95 €49.37 €58.71 €57.63 €78.52 €99.97 €67.05 €99.41 €108.06 €57.97 €99.82 €130.46 €130.74 €45.24 €56.24 €125.47 €74.44 €74.81 €71.68 €132.07 €71.16 €57.3 €66.74 €60.26 €62.7 €163.47 €133.65 €45.29 €112.75 €69.01 €95.59 €67.58 €75.25 €91.67 €122.22 €48.4 €164.05 €135.34 €156.9 €138.15 €117.5 €58.2 €70.55 €69.56 €127.41 €53.34 €119.36 €159.11 €91.7 €75.08 €116.3 €56.9 €149.58 €111.42 €23.82 €36.89 €52.98 €63.33 €177.16 €112.75 €55.6 €159.42 €43.83 €69.82 €140.49 €71.77 €171.62 €126.93 €55.35 €60.14 €113.81 €45.04 €47.94 €145.91 €132.24 €80.24 €120.16 €102.09 €52.74 €40.35 €48.93 €149.31 €45.98 €44.27 €71.74 €68.43 €74.27 €74.95 €54.07 €115.25 €62.33 €60.13 €141.93 €58.48 €158.42 €42.96 €106.14 €93.65 €60.5 €110.25 €68.08 €78.68 €56.67 €48.02 €71.03 €59.75 €80.04 €75.29 €56.91 €128.59 €114.56 €84.57 €129.36 €94.69 €123.3 €146.33 €63.31 €80.18 €38.38 €54.89 €76.26 €69.67 €45.51 €70.41 €67.82 €147.32 €42.64 €152.43 €80.77 €169.69 €67.24 €131.09 €119.35 €42.74 €25.94 €141.22 €42.07 €140.25 €50.44 €98.21 €66.75 €134.06 €53.44 €58.1 €76.75 €94.86 €66.52 €152.32 €131.91 €73.44 €89.91 €108.75 €148.09 €48.24 €52.94 €73.03 €72.53 €49.73 €115.97 €61.28 €105.5 €37.88 €64.94 €137.79 €117.87 €65.74 €69.19 €129.12 €165.99 €49.8 €65.09 €47.69 €72.75 €75.4 €74.6 €46.95 €81.36 €36.8 €47.4 €76.46 €72.02 €53.3 €49.08 €104.97 €68.9 €89.38 €123.54 €97.04 €86.43 €45.77 €135.49 €83.05 €100.85 €116.33 €71.85 €52.11 €44.04 €132.62 €153.54 €129.09 €100.52 €69.14 €60.19 €46.16 €67.58 €80.6 €128.27 €96.95 €139.54 €150.22 €86.73 €47.47 €42.19 €54.76 €76.32 €84.6 €66.88 €86.09 €112.6 €59.76 €124.06 €79.32 €59.14 €67.03 €75.34 €70.35 €140.71 €71.84 €52.72 €119.8 €158.97 €141.05 €38.44 €69.92 €76.64 €99.03 €124.59 €65.83 €138.75 €64.89 €80.08 €66.94 €134.1 €151.82 €74.85 €49.34 €43.44 €69.3 €59.49 €35.27 €57.5 €58.05 €147.68 €85.0 €109.33 €117.24 €104.76 €86.51 €137.54 €46.18 €129.52 €166.19 €49.26 €81.64 €46.33 €39.38 €141.79 €33.91 €121.44 €145.01 €121.14 €163.08 €63.9 €74.93 €67.05 €84.68 €147.7 €103.49 €140.02 €142.07 €126.89 €57.27 €56.5 €99.61 €122.87 €119.2 €99.34 €123.99 €44.55 €75.99 €67.96 €62.85 €72.32 €93.95 €145.07 €54.14 €65.19 €133.84 €106.09 €50.35 €71.06 €81.56 €80.57 €131.06 €46.79 €154.21 €150.18 €53.45 €51.67 €68.12 €131.69 €86.49 €149.44 €95.5 €87.09 €134.6 €61.2 €35.07 €54.26 €154.59 €97.92 €44.28 €118.82 €76.27 €75.91 €128.14 €130.55 €156.6 €150.1 €77.77 €54.77 €82.73 €61.91 €61.42 €129.09 €72.22 €65.83 €99.74 €65.54 €90.04 €83.49 €68.64 €155.17 €112.39 €128.25 €59.08 €157.11 €84.75 €64.13 €109.82 €66.5 €135.03 €126.05 €66.98 €63.11 €62.04 €47.11 €77.67 €71.89 €87.69 €43.79 €130.58 €64.04 €116.3 €144.6 €71.04 €149.31 €124.89 €144.83 €91.69 €56.01 €51.33 €162.66 €54.85 €48.23 €79.25 €48.96 €87.56 €171.93 €124.2 €74.76 €43.9 €43.63 €78.97 €120.91 €51.72 €46.31 €98.62 €44.37 €81.94 €64.1 €73.0 €134.23 €66.69 €116.33 €49.63 €59.99 €50.07 €136.56 €67.98 €104.2 €50.63 €135.7 €136.03 €92.34 €106.49 €85.57 €148.38 €92.76 €67.62 €45.03 €52.04 €125.94 €62.5 €72.21 €102.61 €77.23 €53.56 €68.06 €64.14 €79.85 €84.31 €194.54 €63.61 €47.89 €64.5 €112.37 €61.66 €70.82 €58.49 €95.43 €133.92 €58.06 €96.86 €132.08 €111.6 €112.51 €64.18 €181.15 €139.38 €83.66 €73.47 €50.23 €56.1 €131.13 €162.5 €75.97 €67.38 €94.94 €90.67 €95.0 €141.73 €93.81 €42.19 €58.91 €126.86 €113.37 €75.44 €97.78 €54.94 €83.01 €118.15 €110.43 €141.08 €89.52 €84.74 €81.85 €64.42 €90.42 €126.85 €49.15 €64.4 €54.35 €108.44 €46.67 €44.93 €64.34 €46.18 €107.56 €70.02 €66.8 €66.91 €54.84 €143.81 €123.12 €66.44 €56.37 €109.65 €128.49 €85.49 €46.07 €131.46 €143.0 €58.24 €152.79 €137.48 €84.11 €50.38 €50.78 €156.44 €76.43 €66.66 €82.86 €88.29 €135.63 €34.84 €79.78 €76.39 €137.34 €143.9 €142.6 €160.24 €71.93 €110.15 €144.63 €42.24 €123.44 €79.42 €163.45 €62.47 €37.64 €122.98 €52.35 €46.61 €65.27 €72.97 €71.42 €126.96 €69.35 €112.28 €114.49 €46.29 €121.68 €61.2 €92.36 €103.79 €64.26 €82.93 €58.11 €130.8 €70.05 €47.8 €86.82 €40.72 €50.91 €129.09 €68.11 €52.57 €80.01 €67.85 €111.81 €145.18 €99.15 €82.16 €85.82 €86.89 €55.73 €53.12 €120.57 €55.69 €140.11 €145.73 €126.32 €26.88 €82.54 €102.04 €59.47 €37.06 €63.01 €136.72 €77.92 €120.39 €130.94 €73.93 €65.17 €156.8 €42.34 €69.12 €63.67 €61.6 €120.51 €117.64 €106.24 €85.93 €71.44 €146.19 €151.87 €56.12 €63.28 €64.49 €130.09 €52.16 €132.59 €41.89 €100.3 €91.75 €127.03 €148.95 €84.56 €72.1 €67.12 €49.68 €124.22 €66.53 €156.05 €80.75 €135.02 €107.85 €45.99 €141.81 €47.77 €131.67 €148.83 €124.46 €75.25 €74.49 €41.4 €89.73 €162.94 €119.19 €148.47 €123.35 €67.34 €67.87 €103.59 €155.42 €78.19 €119.42 €47.5 €49.16 €53.93 €96.72 €68.65 €54.93 €51.89 €61.36 €117.13 €53.92 €47.95 €52.8 €94.89 €57.95 €89.78 €66.27 €86.22 €138.1 €54.82 €83.07 €76.83 €62.32 €51.84 €93.7 €60.17 €124.88 €51.56 €114.78 €90.05 €68.59 €78.07 €138.38 €63.05 €143.16 €89.27 €54.87 €83.7 €70.93 €63.81 €148.29 €86.38 €116.09 €136.36 €84.09 €54.68 €43.27 €130.0 €57.46 €79.58 €100.3 €105.65 €116.85 €99.31 €46.14 €64.51 €58.33 €48.36 €88.57 €59.76 €43.5 €160.33 €149.43 €119.2 €110.15 €70.24 €59.01 €107.3 €152.4 €65.38 €105.95 €60.2 €49.65 €130.21 €92.2 €54.52 €67.33 €62.36 €114.04 €143.11 €59.06 €70.75 €65.23 €81.42 €64.96 €73.02 €122.91 €100.0 €34.38 €44.14 €106.53 €64.17 €34.24 €64.44 €164.11 €55.28 €121.23 €47.85 €67.48 €99.97 €98.33 €83.4 €47.91 €124.01 €47.93 €152.88 €136.16 €61.5 €33.83 €108.82 €80.7 €134.62 €136.1 €112.55 €159.59 €111.35 €61.46 €53.39 €148.37 €110.81 €59.13 €74.8 €66.82 €56.25 €78.44 €139.63 €132.74 €63.54 €48.78 €76.9 €38.2 €75.48 €65.74 €59.91 €26.04 €27.33 €124.07 €95.34 €53.45 €131.4 €73.27 €61.32 €147.12 €113.75 €47.15 €156.11 €43.18 €89.31 €76.49 €136.53 €40.63 €98.38 €63.42 €59.47 €46.29 €60.7 €84.46 €68.18 €158.25 €59.82 €60.64 €141.25 €137.59 €81.48 €48.93 €138.59 €159.49 €49.53 €95.36 €78.94 €130.88 €107.47 €120.89 €112.0 €163.76 €134.43 €71.52 €68.9 €108.86 €94.88 €156.71 €81.89 €77.4 €65.81 €84.09 €42.89 €149.8 €55.4 €75.0 €61.54 €45.79 €111.98 €59.18 €53.84 €77.84 €34.95 €92.92 €42.65 €92.12 €63.35 €160.37 €58.55 €154.86 €50.36 €75.54 €164.05 €76.49 €174.07 €100.94 €103.2 €57.32 €84.56 €127.14 €105.37 €37.97 €150.61 €76.64 €147.59 €62.99 €71.05 €70.81 €48.44 €102.96 €65.21 €73.55 €55.56 €51.96 €59.39 €39.56 €70.39 €76.02 €62.0 €124.29 €72.46 €55.8 €99.24 €71.85 €74.4 €93.27 €54.75 €42.96 €70.93 €50.81 €115.02 €94.62 €62.64 €133.49 €91.99 €41.06 €118.25 €62.7 €143.88 €70.71 €79.92 €55.29 €38.71 €146.89 €75.88 €52.7 €77.79 €135.12 €63.94 €66.18 €72.95 €52.98 €82.2 €69.03 €79.65 €113.5 €69.52 €160.43 €41.4 €139.3 €51.46 €55.71 €118.63 €83.1 €60.45 €64.2 €71.34 €144.42 €130.9 €85.9 €40.42 €119.31 €43.93 €36.4 €47.57 €52.87 €68.12 €63.39 €52.29 €117.41 €88.5 €138.41 €126.4 €45.61 €54.13 €91.85 €62.75 €131.73 €148.3 €107.46 €99.16 €45.06 €51.18 €43.18 €90.6 €150.79 €79.2 €72.27 €146.13 €136.02 €64.25 €47.71 €86.48 €157.49 €79.3 €66.04 €89.72 €138.42 €144.76 €76.01 €45.55 €40.53 €61.1 €81.06 €48.39 €67.65 €68.07 €55.83 €90.94 €54.13 €58.44 €54.97 €131.89 €72.05 €48.99 €99.79 €170.37 €98.04 €55.32 €73.41 €123.51 €78.2 €28.75 €105.51 €125.58 €124.34 €77.89 €37.03 €138.15 €68.5 €139.56 €117.08 €65.15 €83.6 €136.54 €146.35 €134.19 €136.03 €160.49 €129.24 €35.13 €136.39 €74.19 €69.85 €88.42 €78.4 €152.62 €58.73 €71.49 €57.95 €34.85 €80.92 €179.24 €83.55 €116.69 €127.44 €122.74 €52.65 €57.09 €86.9 €67.25 €172.26 €55.62 €33.99 €104.59 €129.28 €46.0 €141.71 €53.88 €56.57 €131.93 €132.98 €143.18 €40.29 €84.67 €53.47 €87.33 €165.05 €39.19 €65.56 €67.36 €51.22 €114.19 €65.05 €146.68 €130.71 €107.61 €63.38 €36.05 €39.89 €71.82 €84.67 €57.93 €101.21 €93.41 €109.91 €69.66 €121.01 €46.67 €45.69 €89.25 €44.68 €130.22 €115.45 €70.54 €59.08 €40.46 €118.93 €152.55 €69.28 €72.01 €65.41 €146.73 €40.44 €97.36 €44.56 €148.36 €125.55 €110.11 €67.52 €56.51 €78.75 €148.32 €63.78 €107.63 €133.85 €76.36 €98.41 €80.34 €120.26 €124.32 €161.55 €75.36 €56.21 €66.73 €111.82 €125.06 €88.69 €46.12 €62.85 €59.18 €89.91 €130.52 €46.59 €160.54 €41.96 €75.27 €92.19 €108.44 €43.58 €79.68 €64.53 €46.48 €53.68 €51.61 €48.12 €71.66 €81.2 €63.97 €72.23 €68.74 €187.94 €52.82 €77.27 €54.52 €122.04 €155.86 €140.07 €79.78 €110.63 €107.22 €64.14 €98.79 €54.94 €130.13 €133.41 €51.49 €87.62 €106.54 €151.97 €55.72 €153.31 €93.01 €50.77 €70.99 €51.69 €34.13 €138.54 €120.18 €57.4 €33.24 €56.77 €48.82 €45.77 €42.98 €55.56 €33.88 €105.0 €61.1 €104.72 €76.22 €126.36 €154.36 €116.58 €59.8 €96.76 €51.5 €66.16 €44.56 €157.28 €144.27 €147.18 €117.52 €63.86 €63.45 €84.31 €96.42 €163.38 €102.77 €86.64 €107.39 €68.97 €75.92 €89.06 €30.55 €57.55 €139.11 €125.48 €103.3 €74.77 €94.99 €60.28 €74.42 €59.17 €127.99 €76.42 €61.6 €65.64 €128.46 €110.49 €66.82 €50.73 €100.44 €53.22 €133.36 €73.41 €33.92 €90.82 €56.69 €107.87 €58.14 €74.28 €119.88 €66.08 €63.58 €71.12 €95.29 €143.1 €116.79 €84.71 €52.7 €45.58 €149.24 €168.33 €40.81 €140.36 €99.81 €130.22 €78.22 €73.38 €90.36 €144.47 €124.43 €87.77 €45.9 €69.38 €59.95 €74.63 €90.13 €96.75 €67.58 €82.46 €135.12 €103.55 €164.33 €101.67 €36.65 €78.03 €66.23 €141.91 €123.92 €51.84 €70.06 €131.33 €51.57 €57.13 €59.59 €37.11 €77.74 €117.03 €51.73 €142.2 €77.48 €159.09 €74.09 €40.54 €75.77 €81.82 €51.17 €68.57 €102.57 €95.37 €73.99 €91.35 €75.14 €142.37 €86.01 €152.41 €62.31 €56.69 €94.16 €121.78 €65.64 €70.38 €99.14 €146.49 €58.59 €77.35 €54.12 €94.97 €158.38 €128.19 €137.81 €115.78 €99.14 €145.57 €61.8 €124.07 €33.87 €55.36 €134.49 €57.92 €61.56 €69.95 €153.67 €90.53 €77.84 €86.32 €69.56 €58.66 €77.93 €40.79 €76.5 €112.22 €121.86 €130.32 €50.25 €170.15 €41.91 €63.53 €98.9 €84.18 €63.59 €59.9 €139.1 €52.95 €104.62 €61.4 €152.99 €57.83 €117.35 €97.26 €62.61 €118.69 €49.06 €111.69 €127.84 €157.35 €185.47 €50.73 €80.95 €50.53 €121.32 €109.37 €53.72 €84.39 €140.28 €60.96 €88.39 €157.02 €51.45 €142.13 €48.09 €161.42 €104.26 €146.31 €100.96 €71.51 €110.5 €145.93 €133.33 €50.71 €49.86 €114.26 €53.99 €43.62 €76.08 €71.81 €167.23 €117.2 €89.97 €122.97 €156.78 €70.68 €108.34 €54.17 €89.39 €132.28 €135.67 €82.34 €55.09 €69.64 €99.21 €68.72 €78.46 €57.88 €88.13 €54.21 €26.13 €67.81 €27.97 €84.41 €76.79 €56.38 €152.4 €68.09 €85.26 €172.19 €80.04 €46.73 €62.31 €71.24 €94.42 €37.53 €65.6 €61.01 €59.91 €49.44 €42.06 €116.88 €60.51 €72.69 €176.55 €130.93 €128.75 €85.12 €39.99 €78.94 €77.58 €48.45 €62.8 €46.23 €111.96 €55.14 €99.17 €73.68 €94.18 €130.19 €134.55 €91.35 €95.72 €93.1 €43.45 €60.44 €74.04 €51.34 €122.68 €158.66 €112.75 €67.43 €92.74 €48.11 €24.0 €95.96 €108.27 €143.04 €92.68 €104.04 €130.71 €86.57 €146.47 €184.14 €155.36 €57.53 €76.58 €76.81 €96.98 €137.82 €37.55 €163.94 €101.02 €57.08 €113.43 €153.94 €74.07 €57.77 €84.59 €152.31 €140.39 €103.89 €43.05 €127.84 €112.07 €75.65 €72.47 €57.35 €57.62 €74.42 €80.16 €65.17 €60.47 €35.14 €77.72 €50.09 €87.47 €61.73 €44.3 €110.38 €65.76 €40.46 €52.52 €121.36 €79.86 €142.03 €128.57 €60.67 €59.25 €48.07 €95.28 €130.01 €83.72 €49.43 €42.89 €141.65 €69.22 €103.0 €137.54 €71.07 €63.64 €55.7 €88.81 €136.2 €58.94 €131.29 €98.78 €44.79 €149.42 €76.68 €84.46 €65.17 €54.2 €72.4 €128.2 €114.02 €52.25 €79.77 €125.65 €59.97 €35.93 €115.17 €67.07 €80.38 €131.55 €62.89 €90.47 €157.55 €79.49 €144.83 €148.01 €74.55 €57.38 €83.82 €74.96 €56.04 €78.29 €106.32 €128.54 €60.67 €131.6 €28.12 €129.41 €75.59 €61.55 €57.32 €122.47 €60.79 €112.3 €103.52 €134.87 €97.96 €95.89 €31.65 €54.18 €47.58 €48.72 €63.57 €117.48 €97.22 €60.79 €144.44 €78.01 €107.33 €77.67 €152.2 €160.26 €57.62 €70.98 €107.56 €79.74 €59.94 €55.93 €50.09 €108.66 €57.2 €85.27 €86.11 €147.46 €55.21 €64.71 €118.63 €103.44 €74.0 €72.18 €63.96 €35.22 €41.24 €93.31 €49.23 €140.7 €79.62 €92.04 €151.33 €51.51 €78.15 €100.43 €54.1 €151.82 €62.69 €152.03 €83.39 €41.3 €69.89 €88.44 €109.74 €44.71 €57.76 €69.17 €130.17 €91.9 €87.88 €60.29 €145.6 €145.72 €37.51 €29.54 €151.48 €43.61 €122.53 €53.7 €67.43 €141.7 €119.25 €104.31 €130.7 €136.32 €48.82 €72.5 €65.08 €158.07 €52.08 €57.04 €143.59 €90.0 €42.73 €48.44 €86.14 €50.74 €113.88 €57.5 €124.57 €40.93 €131.67 €46.78 €61.97 €93.22 €100.84 €88.17 €92.33 €92.25 €46.72 €91.53 €96.53 €58.89 €142.81 €73.01 €63.93 €46.35 €98.19 €66.0 €140.88 €79.72 €35.17 €49.87 €55.41 €133.52 €63.77 €105.75 €61.97 €62.49 €99.35 €49.33 €65.06 €56.49 €60.97 €65.38 €51.81 €49.13 €95.81 €63.97 €79.77 €102.2 €99.4 €33.89 €73.32 €91.7 €60.08 €44.79 €66.01 €47.13 €153.72 €53.73 €42.52 €47.65 €90.93 €116.42 €135.58 €74.98 €43.95 €59.81 €102.05 €62.11 €44.59 €78.71 €58.73 €89.14 €97.89 €135.99 €55.43 €146.64 €129.09 €75.2 €75.08 €75.11 €80.85 €81.35 €114.62 €69.94 €42.19 €88.28 €103.44 €48.72 €116.06 €75.97 €60.17 €71.21 €64.54 €57.94 €71.89 €123.77 €147.24 €67.19 €40.26 €128.53 €139.96 €37.82 €118.02 €101.63 €46.04 €148.19 €91.86 €137.33 €138.12 €155.84 €94.67 €129.89 €66.29 €106.75 €81.85 €70.58 €71.81 €62.86 €63.08 €100.46 €51.5 €84.2 €95.77 €104.84 €69.8 €55.6 €129.15 €124.18 €31.31 €46.35 €57.03 €87.56 €56.55 €50.07 €70.6 €55.29 €50.06 €77.95 €83.79 €165.74 €66.41 €50.35 €134.25 €59.12 €73.71 €51.71 €54.67 €121.46 €140.34 €49.74 €50.08 €41.58 €61.96 €48.22 €153.57 €58.13 €139.37 €105.26 €127.95 €88.25 €61.99 €138.59 €41.94 €46.98 €57.42 €56.04 €137.3 €63.15 €71.87 €51.48 €50.84 €99.41 €90.33 €138.29 €141.23 €116.05 €72.52 €121.04 €44.99 €82.67 €57.33 €131.22 €75.94 €99.09 €60.5 €167.43 €118.82 €125.3 €55.03 €108.16 €75.35 €43.67 €46.48 €98.52 €71.76 €47.32 €120.23 €58.37 €86.31 €120.89 €109.11 €59.67 €141.21 €119.89 €78.92 €81.64 €129.16 €66.3 €55.35 €79.44 €95.73 €92.19 €62.51 €47.39 €133.76 €53.64 €148.27 €61.25 €113.44 €83.0 €29.94 €76.27 €150.19 €55.72 €154.25 €134.85 €60.87 €93.76 €62.31 €72.96 €78.01 €27.7 €44.58 €138.37 €54.39 €97.62 €84.26 €74.36 €139.17 €75.45 €62.56 €94.21 €76.92 €152.84 €133.91 €124.94 €141.66 €75.81 €82.64 €154.21 €106.95 €94.01 €124.19 €62.82 €94.57 €79.3 €59.68 €55.29 €79.92 €60.28 €97.16 €71.16 €54.13 €162.53 €60.92 €54.71 €43.83 €64.5 €52.8 €81.34 €73.27 €105.68 €129.72 €49.71 €68.93 €42.84 €138.1 €43.75 €79.07 €99.23 €88.54 €74.0 €74.99 €90.3 €79.98 €83.41 €50.3 €109.94 €95.28 €72.61 €78.53 €57.77 €124.07 €128.34 €75.4 €123.65 €39.26 €58.72 €112.8 €89.83 €84.23 €57.15 €132.97 €106.04 €42.46 €87.49 €56.59 €52.61 €58.68 €48.14 €44.52 €101.23 €76.77 €65.33 €123.44 €37.67 €81.15 €50.13 €143.5 €44.61 €133.87 €150.89 €40.51 €88.29 €161.75 €150.34 €68.0 €96.73 €71.52 €142.18 €70.91 €53.81 €99.01 €65.25 €127.65 €84.76 €138.83 €128.91 €153.36 €64.16 €99.16 €79.26 €92.48 €117.99 €64.63 €127.88 €120.47 €84.82 €124.35 €48.31 €70.78 €90.44 €54.2 €117.12 €138.63 €71.2 €135.89 €35.44 €94.92 €57.66 €131.04 €62.11 €63.12 €63.75 €55.45 €65.95 €57.11 €44.89 €49.99 €43.11 €46.79 €46.26 €82.09 €78.3 €44.61 €129.37 €50.36 €154.06 €103.23 €57.25 €81.99 €64.0 €88.05 €44.02 €71.42 €151.02 €119.59 €96.28 €60.07 €124.42 €55.8 €61.94 €61.94 €129.32 €81.31 €102.52 €85.88 €155.08 €72.28 €95.53 €98.62 €89.03 €140.61 €106.69 €76.49 €143.3 €125.39 €71.44 €109.56 €106.59 €59.99 €112.69 €141.17 €86.12 €54.07 €57.37 €75.36 €67.13 €70.93 €152.16 €111.97 €45.72 €98.26 €72.83 €40.82 €152.51 €46.46 €79.81 €62.74 €97.57 €60.44 €74.33 €88.83 €90.92 €40.2 €132.3 €53.26 €111.65 €52.7 €33.67 €132.74 €138.7 €140.98 €104.46 €56.86 €95.59 €68.77 €49.04 €77.4 €137.9 €92.13 €80.89 €142.87 €134.79 €44.12 €123.48 €139.8 €74.1 €98.82 €126.85 €136.56 €39.17 €59.1 €148.17 €50.9 €124.86 €122.19 €41.27 €29.58 €60.45 €142.46 €46.05 €81.99 €72.37 €113.39 €122.25 €62.19 €74.26 €125.21 €115.37 €57.51 €74.27 €92.34 €61.02 €80.77 €68.64 €148.75 €68.4 €49.91 €53.05 €96.0 €60.45 €37.23 €99.84 €73.34 €82.23 €75.49 €157.71 €106.04 €36.67 €57.89 €147.19 €95.97 €73.09 €70.54 €67.16 €124.28 €108.21 €73.87 €63.74 €108.4 €50.66 €51.49 €148.17 €37.77 €76.82 €71.69 €86.98 €133.68 €145.11 €84.2 €99.17 €60.12 €66.06 €92.85 €45.57 €58.02 €44.66 €119.7 €68.73 €110.89 €83.83 €149.1 €66.7 €135.42 €89.81 €133.97 €43.54 €144.22 €69.16 €41.33 €165.25 €155.75 €78.82 €50.98 €43.77 €69.97 €45.36 €28.46 €147.15 €77.02 €43.32 €37.14 €60.91 €79.47 €65.91 €69.9 €138.36 €37.81 €140.3 €48.97 €103.97 €42.94 €108.39 €151.58 €57.72 €133.6 €67.03 €88.79 €63.79 €95.09 €50.45 €58.47 €68.7 €46.24 €64.88 €127.79 €77.51 €48.22 €84.34 €82.85 €77.47 €44.69 €47.46 €70.16 €138.36 €150.41 €82.0 €49.71 €68.26 €46.72 €147.57 €111.45 €76.81 €114.81 €140.79 €50.17 €46.43 €60.35 €122.01 €132.5 €148.57 €74.78 €173.28 €133.73 €42.65 €148.85 €158.88 €35.77 €72.66 €54.76 €161.08 €58.88 €64.32 €106.2 €63.28 €72.8 €100.45 €149.75 €144.43 €73.76 €37.18 €56.04 €127.76 €137.62 €67.28 €46.86 €138.97 €60.1 €69.23 €51.48 €124.91 €75.39 €149.49 €130.62 €78.09 €54.42 €41.82 €77.38 €65.04 €50.0 €53.31 €71.22 €63.74 €91.47 €122.18 €40.26 €69.46 €56.33 €63.86 €138.76 €36.81 €121.07 €91.91 €87.44 €44.13 €68.67 €47.37 €78.4 €81.29 €136.97 €129.09 €149.8 €65.36 €42.46 €45.12 €144.31 €67.69 €127.9 €89.19 €94.35 €87.16 €80.87 €42.49 €45.03 €135.59 €84.67 €151.2 €80.48 €135.93 €64.95 €48.59 €104.0 €51.15 €88.56 €123.65 €84.13 €89.58 €125.03 €67.18 €55.21 €62.53 €80.9 €131.69 €92.62 €121.86 €56.21 €48.7 €166.44 €105.04 €65.5 €62.92 €62.14 €88.41 €48.97 €64.99 €95.34 €116.04 €85.87 €116.35 €122.45 €140.99 €143.48 €90.91 €149.32 €129.64 €82.65 €40.82 €63.42 €51.37 €67.77 €141.55 €127.82 €131.91 €37.87 €61.58 €61.36 €59.48 €73.57 €156.19 €80.66 €158.25 €58.14 €70.4 €161.62 €61.92 €145.48 €144.06 €37.39 €81.83 €59.04 €53.39 €57.28 €135.6 €150.28 €132.43 €103.15 €57.77 €71.16 €104.45 €56.05 €91.63 €73.07 €95.52 €63.45 €38.27 €134.06 €90.66 €60.48 €55.48 €50.66 €84.72 €44.81 €86.35 €58.45 €105.33 €63.71 €121.62 €52.29 €50.46 €99.25 €86.01 €119.19 €144.13 €35.14 €153.25 €97.72 €98.59 €66.18 €69.0 €73.68 €55.99 €134.75 €66.08 €103.69 €55.85 €87.72 €54.29 €59.83 €97.06 €92.75 €67.2 €82.77 €132.9 €80.14 €119.0 €149.29 €118.56 €114.21 €72.65 €66.76 €69.67 €112.93 €63.34 €72.54 €152.93 €73.94 €65.24 €70.71 €48.49 €134.48 €107.9 €82.65 €140.86 €65.79 €46.16 €91.44 €100.15 €124.92 €70.53 €85.66 €88.25 €65.6 €56.09 €69.07 €53.53 €90.91 €44.9 €90.87 €56.26 €106.73 €125.43 €84.5 €47.48 €94.77 €146.93 €45.01 €82.21 €101.34 €51.89 €52.63 €141.07 €43.12 €95.36 €73.21 €154.87 €136.49 €125.53 €110.32 €138.07 €79.91 €62.8 €66.69 €132.68 €79.35 €86.86 €40.13 €143.29 €161.48 €142.75 €49.33 €147.93 €87.13 €50.25 €73.31 €53.8 €123.11 €78.78 €114.01 €136.29 €122.07 €99.63 

Cela ne fonctionne pas car la colonne `prix` de `df` contient des éléments de type `str` et non des valeurs numériques. Il va donc falloir les transformer au format adéquat.

1. Enlevez les signes superflus (€) et convertissez la colonne au format numérique `float`.

In [10]:
## Écrivez votre code ici.
def supprimestr(x):
  x=x[:-1]
  return float(x)

df["prix"]=df["prix"].apply(supprimestr)

2. Réessayez d'obtenir le prix moyen.

In [11]:
## Écrivez votre code ici.
print(df['prix'].mean())

87.71348666666667

3. Obtenez toutes les informations pertinentes sur les prix avec la méthode `describe`.

In [12]:
## Écrivez votre code ici.
df['prix'].describe()

count    3000.000000
mean       87.713487
std        35.460943
min        23.820000
25%        59.032500
50%        78.450000
75%       117.267500
max       194.540000
Name: prix, dtype: float64

## Exercice 3

On nous informe que les objets proviennent de deux entrepôts différents, identifiés par le préfixe de leur `id` :

AM-... : Entrepôt d'Amsterdam.

BER-... : Entrepôt de Berlin.

La partie alphanumérique qui suit est le véritable identifiant des objets.

Nous souhaitons nettoyer les identifiants afin de pouvoir trier les objets en fonction de leur véritables identifiants. Il s'agit donc de renvoyer l'information de l'entrepôt d'origine à une autre colonne.

1. Créez une nouvelle colonne `entrepot`. Remplissez-la avec la valeur "Amsterdam" si l'id commence par "AM-", et "Berlin" s'il commence par "BER-".

Indice :  Vous pouvez utiliser la fonction `np.where` (**[documentation](https://numpy.org/devdocs/reference/generated/numpy.where.html)**).

In [13]:
## Écrivez votre code ici
df["entrepot"] = np.where( df["id"].str.startswith("AM-"),"Amsterdam",
    "Berlin"
)
## alternative du prof : df["entrepot"] = np.where(df["id"].str[0]=='A',"Amsterdam", "Berlin")

2. Quel est le prix moyen des objets venant d'Amsterdam ? Celui des objets venant de Berlin ?

In [14]:
## Écrivez votre code ici.
df.groupby("entrepot")['prix'].mean

3. Modifiez la colonne `id` pour ne conserver que le code alphanumérique (la partie après le tiret -).

In [15]:
## Écrivez votre code ici.
df["id"]=df["id"].str.split('-').str[1]
##voir ce qu 'est split

4. Triez le DataFrame par ordre alphabétique des nouveaux id, puis réinitialisez l'index pour qu'il soit continu (de 0 à N-1).

In [16]:
## Écrivez votre code ici.

df=df.sort_values(by="id").reset_index(drop=True)
df.head()

      id   prix                                              image   entrepot
0  014IW  46.12  0 0 0 0 0 0 0 0 0 0 178 143 137 142 108 117 10...  Amsterdam
1  019W1  84.31  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 0 0 0 0...  Amsterdam
2  01EJA  41.06  0 0 0 0 0 0 0 0 0 0 72 107 75 73 53 51 63 86 6...     Berlin
3  01FCG  70.42  0 0 0 0 0 0 0 0 90 235 198 204 205 204 203 203...  Amsterdam
4  01MRT  28.75  0 0 0 0 0 0 0 0 0 0 97 109 87 86 93 103 99 130...  Amsterdam

## Exercice 4

La colonne `image` contient actuellement une chaîne de caractères (ex: '0 255 12 ...'). Pour que nos algorithmes puissent 'voir' l'image, nous devons éclater cette chaîne en 784 colonnes distinctes (une par pixel). Chaque colonne représentera l'intensité lumineuse d'un point de l'image.

1. Utilisez une méthode de chaîne pour séparer la colonne image en un nouveau DataFrame nommé pixels. Chaque valeur séparée par un espace doit devenir une colonne distincte.

In [17]:
## Écrivez votre code ici.
pixels = df['image'].str.split(' ', expand=True)

2. Affichez les dimensions de ce nouveau DataFrame `pixels` et ses premières lignes.

In [18]:
## Écrivez votre code ici.
print(pixels.shape)
display(pixels.head())

(3000, 784)

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,175,70,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,84,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,90,235,...,3,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,55,0,0,0,0,0,0,0,0,0

3. Créez également un DataFrame nommé `prix` ne retenant que la colonne prix de `df`. Affichez ses dimensions et ses premières lignes.

In [19]:
## Écrivez votre code ici.

prix = df[['prix']].copy()
print(prix.shape)
display(prix.head())

(3000, 1)

    prix
0  46.12
1  84.31
2  41.06
3  70.42
4  28.75

## Exercise 5

Nous avons un DataFrame `pixels` de la bonne dimension mais il contient des éléments de type `str`. Nous devons donc convertir ce DataFrame au format numérique. De plus, nous savons que ce jeu de donnée est corrompu. Il nous faut donc vérifier que chaque pixel est bien un entier entre 0 et 255. Il faudra alors supprimer toutes les lignes avec des pixels corrompus. Il faudra faire attention à bien retenir quelles lignes sont supprimées car il faudra également enlever ces lignes du DataFrame `prix`.

1. Utilisez `pd.to_numeric` (**[documentation](https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html)**)pour convertir `pixels` au format numérique en faisant en sorte que tout ce qui n'est pas un nombre soit converti en `NaN`.

In [20]:
## Écrivez votre code ici.
pixels = pixels.apply(pd.to_numeric, errors='coerce')

2. Combien de cellules (pixels) contenaient autre chose qu'un nombre ?

In [21]:
## Écrivez votre code ici.
nb_erreurs = pixels.isna().sum().sum()
print(nb_erreurs)

149

3. Vérifiez si tous les cellules ayant un élément numérique contient bien la représentation mathématique d'un pixel (un entier entre 0 et 255) en affichant les minimum et maximum que l'on trouve dans `pixels`.

In [22]:
## Écrivez votre code ici.
min_global = pixels.min().min()
max_global = pixels.max().max()

print(min_global)
print(max_global)

-10.0
999.0

4. Créez un masque booléen `a_jeter` couvrant les lignes avec des valeurs corompues (`Nan` ou nombres absurdes). Cela représente combien de lignes ?

In [25]:
## Écrivez votre code ici.
lignesnan= pixels.isna().any(axis=1)
lignesabsurdes = ((pixels < 0) | (pixels > 255)).any(axis=1)
ajeter = lignesnan | lignesabsurdes
print(ajeter.sum())

465

5. Enlevez de `pixels` et de `prix` les lignes couverte par `a_jeter`. Affichez les nouvelles dimensions.

In [26]:
## Écrivez votre code ici.
pixels = pixels.loc[~ajeter].copy()
prix = prix.loc[~ajeter].copy()
print(pixels.shape)
print(prix.shape)

(2535, 784)
(2535, 1)

## Exercice 6

Nos données sont propres, alignées et débarrassées des erreurs. Cependant, les algorithmes de Machine Learning (comme ceux de Scikit-Learn ou TensorFlow) ne savent pas lire des DataFrames Pandas. Ils ont besoin de matrices numériques pures. La dernière étape est de transformer nos tableaux en objets `np.array` optimisés.

1.  Convertissez `pixels` en un object `np.array` nommé `Pixels`. Étant donné que chaque pixel est un entier entre 0 et 255, il est possible de les stockés au format `uint8` (cela utilise 4 fois moins de mémoire que le format standard).

In [27]:
## Écrivez votre code ici.
Pixels = pixels.to_numpy(dtype='uint8')

2.  Convertissez `prix` en un object `np.array` nommé `Prix`. On choisit le format `float32`.

In [28]:
## Écrivez votre code ici.
Prix = prix.to_numpy(dtype='float32')

3. Affichez les types et les dimensions de `Pixels` et `Prix`.

In [30]:
## Écrivez votre code ici.
print(type(Pixels))
print(Prix)

print(Pixels.shape)
print(Prix.shape)

<class 'numpy.ndarray'>
[[46.12]
 [84.31]
 [41.06]
 ...
 [63.59]
 [91.53]
 [71.34]]
(2535, 784)
(2535, 1)